# Generated by Django 5.1.6 on 2025-03-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='feedback',
            field=models.FileField(blank=True, null=True, upload_to='feedback_pdfs/'),
        ),
    ]
